---
repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7

  - repo: https://github.com/asottile/blacken-docs
    rev: v0.5.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==19.3b0]
        language_version: python3.7

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        args: [--remove]
      - id: trailing-whitespace

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v1.8.0
    hooks:
      - id: reorder-python-imports
