[tool.poetry]
name = "mezzo"
version = "0.0.0"
description = "Wheel package manager"
authors = ["Ethan Paul <e@enp.one>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
